#define ROWS_NUM 4

#define KEYPAD_PORT_R0 'B'
#define KEYPAD_PIN_R0	9

#define KEYPAD_PORT_R1 'B'
#define KEYPAD_PIN_R1	8

#define KEYPAD_PORT_R2 'B'
#define KEYPAD_PIN_R2	7

#define KEYPAD_PORT_R3 'B'
#define KEYPAD_PIN_R3	6

#define COLS_NUM 4

#define KEYPAD_PORT_C0 'B'
#define KEYPAD_PIN_C0	5

#define KEYPAD_PORT_C1 'B'
#define KEYPAD_PIN_C1	4

#define KEYPAD_PORT_C2 'B'
#define KEYPAD_PIN_C2	3

#define KEYPAD_PORT_C3 'A'
#define KEYPAD_PIN_C3	15


#define KEYPAD_ROWS_PORTS 	{KEYPAD_PORT_R0 , KEYPAD_PORT_R1 , KEYPAD_PORT_R2 , KEYPAD_PORT_R3}
#define KEYPAD_ROWS_PINS  	{KEYPAD_PIN_R0 , KEYPAD_PIN_R1 , KEYPAD_PIN_R2 , KEYPAD_PIN_R3}

#define KEYPAD_COLS_PORTS	{KEYPAD_PORT_C0 , KEYPAD_PORT_C0 , KEYPAD_PORT_C0 , KEYPAD_PORT_C0}
#define KEYPAD_COLS_PINS 	{KEYPAD_PIN_C0 , KEYPAD_PIN_C1 , KEYPAD_PIN_C2 , KEYPAD_PIN_C3 }

#define KEYPAD_VALUES {{'1','2','3','3'},{'4','5','6','6'},{'7','8','9','9'},{'e','s','0','0'}}

#define DEFAULT_VALUE 0xFF
